environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "4.2"
    - nodejs_version: "5.2"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm install source-map@0.5.3
  - npm run test
version: "{build}"