environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "4.2"
    - nodejs_version: "5.0"
    - nodejs_version: "5.1"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm run test-cov
version: "{build}"